function B_oe = B_oe_func(in1,L1)
%B_oe_func
%    B_oe = B_oe_func(IN1,L1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    14-Feb-2026 17:40:22

%Inputs: [{oe}; {L}]
oe1 = in1(1,:);
oe2 = in1(2,:);
oe3 = in1(3,:);
oe4 = in1(4,:);
oe5 = in1(5,:);
t2 = cos(L1);
t3 = sin(L1);
t4 = oe2.^2;
t5 = oe3.^2;
t6 = oe4.^2;
t7 = oe5.^2;
t8 = oe2.*t2;
t9 = oe5.*t2;
t10 = oe3.*t3;
t11 = oe4.*t3;
t15 = t6+t7+1.0;
t16 = t4+t5-1.0;
t12 = t8.*2.0;
t13 = t10.*2.0;
t14 = -t11;
t17 = t8+t10+1.0;
t20 = oe1.*t16;
t21 = 1.0./t16;
t18 = t17+1.0;
t19 = t9+t14;
t22 = t12+t13+2.0;
t23 = 1.0./t17;
t24 = -t20;
t25 = 1.0./t22;
t26 = sqrt(t24);
B_oe = reshape([oe1.*t21.*t26.*sin(L1-atan(oe3./oe2)).*sqrt(t4+t5).*-2.0,t3.*t26,-t2.*t26,0.0,0.0,oe1.*t17.*t21.*t26.*-2.0,t23.*t26.*(oe2+t2.*t18),t23.*t26.*(oe3+t3.*t18),0.0,0.0,0.0,oe3.*t19.*t23.*t26,-oe2.*t19.*t23.*t26,t2.*t15.*t25.*t26,t3.*t15.*t25.*t26],[5,3]);
end
