function P = periapsis_penalty_sym(in1,in2,in3,m1,n1,r1,F_max1,W_p1,r_p_min1,k1)
%PERIAPSIS_PENALTY_SYM
%    P = PERIAPSIS_PENALTY_SYM(IN1,IN2,IN3,M1,N1,R1,F_max1,W_p1,R_P_MIN1,K1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    14-Feb-2026 17:40:21

%Inputs: [{oe}; {oe_t}; {W_oe}; {m}; {n}; {r}; {F_max}; {W_p}; {r_p_min}; {k_p}]
oe1 = in1(1,:);
oe2 = in1(2,:);
oe3 = in1(3,:);
P = exp(k1.*((oe1.*(sqrt(oe2.^2+oe3.^2)-1.0))./r_p_min1+1.0));
end
