function oedot_xx = QLaw_oe_max_rate_sym(in1,in2,in3,m1,n1,r1,F_max1,W_p1,r_p_min1,k1)
%QLaw_oe_max_rate_sym
%    OEDOT_XX = QLaw_oe_max_rate_sym(IN1,IN2,IN3,M1,N1,R1,F_max1,W_p1,R_P_MIN1,K1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    14-Feb-2026 17:40:21

%Inputs: [{oe}; {oe_t}; {W_oe}; {m}; {n}; {r}; {F_max}; {W_p}; {r_p_min}; {k_p}]
oe1 = in1(1,:);
oe2 = in1(2,:);
oe3 = in1(3,:);
oe4 = in1(4,:);
oe5 = in1(5,:);
t2 = oe2.^2;
t3 = oe3.^2;
t4 = oe4.^2;
t5 = oe5.^2;
t6 = t2+t3;
t7 = t4+t5+1.0;
t8 = t6-1.0;
t9 = sqrt(t6);
t10 = oe1.*t8;
t11 = -t10;
t12 = sqrt(t11);
t13 = F_max1.*t12.*2.0;
oedot_xx = [F_max1.*oe1.^(3.0./2.0).*sqrt(-(t9+1.0)./(t9-1.0)).*2.0;t13;t13;(F_max1.*t7.*t12)./(oe2.*2.0+sqrt(-t3+1.0).*2.0);(F_max1.*t7.*t12)./(oe3.*2.0+sqrt(-t2+1.0).*2.0)];
end
