function Q = Q_func_sym(in1,in2,in3,m1,n1,r1,F_max1,W_p1,r_p_min1,k1)
%Q_func_sym
%    Q = Q_func_sym(IN1,IN2,IN3,M1,N1,R1,F_max1,W_p1,R_P_MIN1,K1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    12-Feb-2026 15:03:17

%Inputs: [{oe}; {oe_t}; {W_oe}; {m}; {n}; {r}; {F_max}; {W_p}; {r_p_min}; {k_p}]
W_oe1 = in3(1,:);
W_oe2 = in3(2,:);
W_oe3 = in3(3,:);
W_oe4 = in3(4,:);
W_oe5 = in3(5,:);
oe1 = in1(1,:);
oe2 = in1(2,:);
oe3 = in1(3,:);
oe4 = in1(4,:);
oe5 = in1(5,:);
oe_t1 = in2(1,:);
oe_t2 = in2(2,:);
oe_t3 = in2(3,:);
oe_t4 = in2(4,:);
oe_t5 = in2(5,:);
t2 = oe2.^2;
t3 = oe3.^2;
t4 = oe4.^2;
t5 = oe5.^2;
t6 = 1.0./F_max1.^2;
t7 = -oe_t1;
t8 = 1.0./oe1;
t9 = oe1+t7;
t10 = t2+t3;
t11 = t4+t5+1.0;
t12 = t10-1.0;
t13 = sqrt(t10);
t14 = 1.0./t11.^2;
t15 = 1.0./t12;
t16 = t13-1.0;
Q = -(W_p1.*exp(k1.*((oe1.*t16)./r_p_min1+1.0))+1.0).*((W_oe2.*t6.*t8.*t15.*(oe2-oe_t2).^2)./4.0+(W_oe3.*t6.*t8.*t15.*(oe3-oe_t3).^2)./4.0+W_oe4.*t6.*t8.*t14.*t15.*(oe2+sqrt(-t3+1.0)).^2.*(oe4-oe_t4).^2.*4.0+W_oe5.*t6.*t8.*t14.*t15.*(oe3+sqrt(-t2+1.0)).^2.*(oe5-oe_t5).^2.*4.0+(W_oe1.*t6.*t8.^3.*t9.^2.*t16.*((abs(t9)./(m1.*oe_t1)).^n1+1.0).^(1.0./r1))./(t13.*4.0+4.0));
end
