function S_oe = QLaw_scaling_sym(in1,in2,in3,m1,n1,r1,F_max1,W_p1,r_p_min1,k1)
%QLaw_scaling_sym
%    S_oe = QLaw_scaling_sym(IN1,IN2,IN3,M1,N1,R1,F_max1,W_p1,R_P_MIN1,K1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    12-Feb-2026 15:03:16

%Inputs: [{oe}; {oe_t}; {W_oe}; {m}; {n}; {r}; {F_max}; {W_p}; {r_p_min}; {k_p}]
oe1 = in1(1,:);
oe_t1 = in2(1,:);
S_oe = [((abs(oe1-oe_t1)./(m1.*oe_t1)).^n1+1.0).^(1.0./r1);1.0;1.0;1.0;1.0];
end
