function x_dot = rotational_3DoF_EoM(t,in2,in3,in4,in5)
%rotational_3DoF_EoM
%    X_DOT = rotational_3DoF_EoM(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    01-Mar-2026 12:28:51

I1 = in5(1,:);
I2 = in5(2,:);
I3 = in5(3,:);
tau1 = in3(1,:);
tau2 = in3(2,:);
tau3 = in3(3,:);
theta1 = in2(1,:);
theta2 = in2(2,:);
theta3 = in2(3,:);
theta4 = in2(4,:);
w1 = in2(5,:);
w2 = in2(6,:);
w3 = in2(7,:);
t2 = -I3;
x_dot = [(theta2.*w3)./2.0-(theta3.*w2)./2.0+(theta4.*w1)./2.0;theta1.*w3.*(-1.0./2.0)+(theta3.*w1)./2.0+(theta4.*w2)./2.0;(theta1.*w2)./2.0-(theta2.*w1)./2.0+(theta4.*w3)./2.0;w1.*conj(theta1).*(-1.0./2.0)-(w2.*conj(theta2))./2.0-(w3.*conj(theta3))./2.0;(tau1+w2.*w3.*(I2+t2))./I1;(tau2-w1.*w3.*(I1+t2))./I2;(tau3+w1.*w2.*(I1-I2))./I3];
end
