function xdot = linearized_relative_orbit_EoM(t,in2,in3,in4,in5)
%linearized_relative_orbit_EoM
%    XDOT = linearized_relative_orbit_EoM(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    26-Feb-2026 14:27:52

Isp1 = in5(7,:);
m1 = in2(7,:);
r1 = in2(1,:);
r2 = in2(2,:);
r3 = in2(3,:);
thrust1 = in3(1,:);
thrust2 = in3(2,:);
thrust3 = in3(3,:);
v1 = in2(4,:);
v2 = in2(5,:);
v3 = in2(6,:);
x_keplerian_c1 = in5(1,:);
x_keplerian_c2 = in5(2,:);
x_keplerian_c6 = in5(6,:);
t2 = x_keplerian_c2.*2.0;
t3 = x_keplerian_c6.*2.0;
t4 = x_keplerian_c2+1.0;
t5 = besselj(1,x_keplerian_c2);
t6 = 1.0./m1;
t7 = x_keplerian_c2-1.0;
t8 = 1.0./x_keplerian_c1;
t9 = t8.^2;
t10 = t8.^3;
t11 = besselj(2,t2);
t12 = t8.*6.3781e+3;
t14 = t4.*t7.*x_keplerian_c1.*1.567865038177514e-4;
t13 = -t12;
t15 = -t14;
t17 = t10.*2.59462126008541e+11;
t16 = sqrt(t15);
t18 = sqrt(t17);
t19 = t.*t18;
t20 = t19.*2.0;
t21 = t19+x_keplerian_c6;
t22 = sin(t21);
t23 = t3+t20;
t24 = sin(t23);
t25 = t5.*t22.*2.0;
t26 = t11.*t24;
t27 = t21+t25+t26;
t28 = cos(t27);
t29 = t28.*x_keplerian_c2;
t30 = t29-1.0;
t31 = 1.0./t30;
t32 = t31.^2;
t33 = t31.^3;
t35 = t8.*t31.*1.27562e+4;
t34 = t32.^2;
t36 = -t35;
t37 = t12+t35;
t38 = t13+t36;
t39 = 1.0./t37;
t41 = t4.*t7.*t17.*t34;
t40 = sqrt(t38);
t43 = t4.*t7.*t8.*t32.*t39.*(-6.3781e+3);
t44 = t43+1.0;
t45 = sqrt(t44);
mt1 = [v1;v2;v3;t6.*thrust1-r1.*(t41+t10.*t33.*5.18924252017082e+11)+t9.*t16.*t32.*v2.*8.136031922e+7+r2.*t10.*t16.*t33.*t40.*t45.*5.18924252017082e+11;t6.*thrust2+r2.*(t17.*t33-t4.*t7.*t10.*t34.*2.59462126008541e+11)-t9.*t16.*t32.*v1.*8.136031922e+7-r1.*t10.*t16.*t33.*t40.*t45.*5.18924252017082e+11;t6.*thrust3+r3.*t17.*t33];
mt2 = [(sqrt(thrust1.^2+thrust2.^2+thrust3.^2).*(-8.058495685842129e+2))./Isp1];
xdot = [mt1;mt2];
end
