function [dM2_M2] = shapiro_M2(y, M2) 
    cons = (1 + ((y - 1) / 2) * M2) / (1 - M2);
    dM2_M2 = cons * [-2,...
                     1 + y * M2,...
                     y * M2,...
                     2 * (1 + y * M2)];
end

function [dV_V] = shapiro_V(y, M2) 
    cons = 1 / (1 - M2);
    dV_V = cons * [-1,...
                     1 + ((y - 1) / 2) * M2,...
                     y * M2 / 2,...
                     1 + y * M2];
end

function [dc_c] = shapiro_c(y, M2) 
    cons = 1 / (1 - M2);
    dc_c = cons * [((y - 1) / 2) * M2,...
                     ((1 + y * M2) / 2) * (1 + ((y - 1) / 2) * M2),...
                     -y * (y - 1) * M2 ^ 2 / 4,...
                     -((y - 1) / 2) * M2 * (1 + y * M2)];
end

function [dT_T] = shapiro_T(y, M2) 
    cons = 1 / (1 - M2);
    dT_T = cons * [(y - 1) * M2,...
                     (1 + y * M2) * (1 + ((y - 1) / 2) * M2),...
                     -y * (y - 1) * M2 ^ 2 / 2,...
                     -(y - 1) * M2 * (1 + y * M2)];
end

function [drho_rho] = shapiro_rho(y, M2) 
    cons = 1 / (1 - M2);
    drho_rho = cons * [M2,...
                     -(1 + ((y - 1) / 2) * M2),...
                     -y * M2 / 2,...
                     -(y + 1) * M2];
end

function [dp_p] = shapiro_p(y, M2)
    cons = y * M2 / (1 - M2);
    dp_p = cons * [1,...
                   -(1 + (y - 1) / 2 * M2),...
                   -(1 + (y - 1) * M2) / 2,...
                   -2 * (1 + (y - 1) / 2 * M2)];
end

function [dp0_p0] = shapiro_p0(y, M2)
    cons = 1;
    dp0_p0 = cons * [0,...
                     -y * M2 / 2,...
                     -y * M2 / 2,...
                     -y * M2];
end

function [dF_F] = shapiro_F(y, M2)
    cons = 1;
    dF_F = cons * [1 / (1 + y * M2),...
                   0,...
                   -y * M2 / (2 * (1 + y * M2)),...
                   0];
end

function [ds_cp] = shapiro_s(y, M2)
    cons = 1;
    ds_cp = cons * [0,...
                    1 + (y - 1) / 2 * M2,...
                    (y - 1) * M2 / 2,...
                    (y - 1) * M2];
end