function xdot = CWH_relative_orbit_EoM(t,in2,in3,in4,in5)
%CWH_relative_orbit_EoM
%    XDOT = CWH_relative_orbit_EoM(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    11-Feb-2026 17:25:25

Isp1 = in5(2,:);
m1 = in2(7,:);
r1 = in2(1,:);
r3 = in2(3,:);
r_c1 = in5(1,:);
thrust1 = in3(1,:);
thrust2 = in3(2,:);
thrust3 = in3(3,:);
v1 = in2(4,:);
v2 = in2(5,:);
v3 = in2(6,:);
t2 = 1.0./m1;
t3 = 1.0./r_c1.^3;
t4 = t3.*2.59462126008541e+11;
t5 = sqrt(t4);
xdot = [v1;v2;v3;r1.*t3.*7.78386378025623e+11+t2.*thrust1+t5.*v2.*2.0;t2.*thrust2-t5.*v1.*2.0;r3.*t3.*(-2.59462126008541e+11)+t2.*thrust3;(sqrt(thrust1.^2+thrust2.^2+thrust3.^2).*(-8.058495685842129e+2))./Isp1];
end
