function xdot = linearized_relative_orbit_EoM(t,in2,in3,in4,in5)
%linearized_relative_orbit_EoM
%    XDOT = linearized_relative_orbit_EoM(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    11-Feb-2026 17:33:05

Isp1 = in5(7,:);
m1 = in2(7,:);
r1 = in2(1,:);
r2 = in2(2,:);
r3 = in2(3,:);
thrust1 = in3(1,:);
thrust2 = in3(2,:);
thrust3 = in3(3,:);
v1 = in2(4,:);
v2 = in2(5,:);
v3 = in2(6,:);
x_keplerian_c1 = in5(1,:);
x_keplerian_c2 = in5(2,:);
x_keplerian_c6 = in5(6,:);
t2 = x_keplerian_c2.*2.0;
t3 = x_keplerian_c6.*2.0;
t4 = x_keplerian_c2+1.0;
t5 = besselj(1,x_keplerian_c2);
t6 = 1.0./m1;
t7 = x_keplerian_c2-1.0;
t8 = 1.0./x_keplerian_c1.^2;
t9 = 1.0./x_keplerian_c1.^3;
t10 = besselj(2,t2);
t11 = t4.*t7.*x_keplerian_c1.*1.567865038177514e-4;
t14 = t9.*2.59462126008541e+11;
t12 = -t11;
t15 = sqrt(t14);
t13 = sqrt(t12);
t16 = t.*t15.*1.61360910081756e+3;
t17 = t.*t15.*8.068045504087801e+2;
t18 = t17+x_keplerian_c6;
t19 = t3+t16;
t20 = sin(t18);
t21 = sin(t19);
t22 = t5.*t20.*2.0;
t23 = t10.*t21;
t24 = t18+t22+t23;
t25 = cos(t24);
t26 = t25.*x_keplerian_c2;
t27 = t26-1.0;
t28 = 1.0./t27.^2;
t29 = 1.0./t27.^3;
t30 = t28.^2;
t31 = t4.*t7.*t14.*t30;
mt1 = [v1;v2;v3;t6.*thrust1-r1.*(t31+t9.*t29.*5.18924252017082e+11)+r2.*t8.*t13.*t28.*4.068015961e+7+t8.*t13.*t28.*v2.*8.136031922e+7;t6.*thrust2+r2.*(t14.*t29-t4.*t7.*t9.*t30.*2.59462126008541e+11)-r1.*t8.*t13.*t28.*4.068015961e+7-t8.*t13.*t28.*v1.*8.136031922e+7;t6.*thrust3+r3.*t14.*t29];
mt2 = [(sqrt(thrust1.^2+thrust2.^2+thrust3.^2).*(-8.058495685842129e+2))./Isp1];
xdot = [mt1;mt2];
end
